### ISSUE TITLE
defaultPickerValue not working

### ISSUE THREAD

**Issue by MobinShoaei** [saeedrahimi/antd-jalali#10]
Hi, thanks for developing this component. 
I think there is a bug in setting defaultPickerValue. and component does not work properly 
please check.
thanks
![213132](https://user-images.githubusercontent.com/83772357/117317128-7a02c600-ae9e-11eb-8aa7-d590c4b140a5.png)
![Screenshot from 2021-05-06 19-05-13](https://user-images.githubusercontent.com/83772357/117317151-7f601080-ae9e-11eb-8aca-b428bf59e4be.png)

**Comment by saeedrahimi** [comment]
Please checkout the new version.
