### ISSUE TITLE
problem with using in nextjs

### ISSUE THREAD

**Issue by SorooshMortazavi** [saeedrahimi/antd-jalali#13]
./node_modules/antd/lib/button/style/index.less
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import '../../style/themes/index';
| @import '../../style/mixins/index';
| @import './mixin';

hi i use antd-jalali in nextjs and have this problem how can i fix that

**Comment by shdezhahanj** [comment]
> ./node_modules/antd/lib/button/style/index.less Module parse failed: Unexpected character '@' (1:0) You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> 
> > @import '../../style/themes/index';
> > | @import '../../style/mixins/index';
> > | @import './mixin';
> 
> hi i use antd-jalali in nextjs and have this problem how can i fix that

I have the same problem! Did you find any solutions!!??

**Comment by SadafZiya** [comment]
I had  this problem too but I install version 0.9.3 and now I don't have this error

**Comment by sepaseh** [comment]
Dear Saeed

There is a problem with Nextjs@12.x.x version, we should use "generatePicker" from "es" path ("antd/es/date-picker/generatePicker") which you did in version 9.0.4 as well.

But added styles have caused an error. Please remove imported antd styles in components like previous version.

**Comment by saeedrahimi** [comment]
A new version has been released.
Tried to solve reported issues.
Example repository for nextjs has been updated to the latest version. (With [swc ](https://nextjs.org/docs/advanced-features/compiler#why-swc)enabled!)
Closing this issue, please feel free to reopen it.
