### ISSUE TITLE
Error calling localized month name formatting after instantiating any controls.

### ISSUE THREAD

**Issue by mohas** [saeedrahimi/antd-jalali#14]
After using any control in my react tree calling `dayjs().locale('fa').format('MMM')` or any other month name formatter will fail.
This s because jalaliday adds a jmonth array to dayjs locale object, while you use your own custom locale object, so calling format, jalaliday expects a jmonth array to be available which is not, thus the error.

I will submit a pull request for a quick fix, but in general I think that you should avoid defining your custom locale object and just use the default dayjs one

**Comment by mohas** [comment]
#15 pull request added

**Comment by saeedrahimi** [comment]
Thank you for your contribution. 
Feel free to reopen this issue.

Closed by #15
