### ISSUE TITLE
this package is large

### ISSUE THREAD

**Issue by mehdiraized** [saeedrahimi/antd-jalali#2]
Why is the package size so large?

![Screen Shot 2020-05-31 at 12 44 44](https://user-images.githubusercontent.com/4368004/83347797-be0b5380-a33c-11ea-8a27-96288ab62802.png)

**Comment by saeedrahimi** [comment]
Hi, thank you for reporting this issue and sorry for late answer.
I've just updated the library and fixed this issue.

![image](https://user-images.githubusercontent.com/12451743/99904747-36e2db00-2ce2-11eb-9b1e-528d966445b4.png)

**Comment by saeedrahimi** [comment]
I am closing this issue, feel free to reopen. Thnx
