### ISSUE TITLE
Name of monthes is not in Jalali

### ISSUE THREAD

**Issue by Masoooud** [saeedrahimi/antd-jalali#3]
In your module name of months are not in Jalala. If it is possible, change them to Jalali months.

**Comment by saeedrahimi** [comment]
Hi, thank you for reporting this issue and sorry for late answer.
I've just updated the library and fixed some issues.
Could you check it please?

**Comment by saeedrahimi** [comment]
I am closing this issue, feel free to reopen. Thnx
