### ISSUE TITLE
Beginning of the first day of the month, with the wrong day

### ISSUE THREAD

**Issue by baharboloor** [saeedrahimi/antd-jalali#35]
Hi

When the last day of the month is Friday, it shows the first day of the next month with the wrong day
for example :
The last day of Day 1400 is Friday
But the first day of the next month, which is Bahman, is displayed from Monday instead of Saturday
![Screenshot (1)](https://user-images.githubusercontent.com/47713208/212685329-35d20e8e-8a33-45ff-8d0e-d9096db39132.png)

**Comment by sadra-allahyari** [comment]
Did you find any solution or any alternative to use instead of antd-jalali?

**Comment by Atefeh-Masoumi** [comment]
I have the same problem did you found any solution

**Comment by sadra-allahyari** [comment]
If you are using the MUI this is a good package you can use for your project:
https://mui.com/toolpad/reference/components/date-picker/
But you have to modify this for persian calendar
