### ISSUE TITLE
Wrong Week Days

### ISSUE THREAD

**Issue by unxoun** [saeedrahimi/antd-jalali#40]
at [saeedrahimi.github.io](https://saeedrahimi.github.io/antd-jalali/) demo
in Jalali Datepicker

dates are assigned to wrong week days.
e.g. "12 Mehr 1402" is displayed as "ی" (Yekshanbeh) whereas it should be "چ" (Chaharshanbeh).

we have the same issue on our own project.

**Comment by farz-msv** [comment]
We have the same issue

**Comment by farhadpesaraklu** [comment]
dates are assigned to wrong week days.

**Comment by Aslan-Khorramie** [comment]
i have used antd-jalali-plus and this issue is still there.

for example the datepicker component returns today as Friday but it should be Tuesday.

any quick solution?

**Comment by thepouria** [comment]
i had the same issue but today i checked the demo again and it seems it have been fixed !

**Comment by saeedrahimi** [comment]
I assume this issue is resolved with the latest changes.
Please feel free to reopen this issue. 🙂
