### ISSUE TITLE
Error hot fix

### ISSUE THREAD

**Issue by mehdiraized** [saeedrahimi/antd-jalali#5]
SyntaxError: Unexpected token 'export'
```
nextjs : 10.0.2
react: 17.0.1
```

![Screen Shot 1399-09-03 at 17 24 23](https://user-images.githubusercontent.com/4368004/99970185-bdfe8480-2db0-11eb-9fee-d52957e13851.png)

**Comment by saeedrahimi** [comment]
fixed in #6
