### ISSUE TITLE
how to set value

### ISSUE THREAD

**Issue by mehdi-ard** [saeedrahimi/antd-jalali#7]
Hi, thanks for this module.
I wanted to give the calendar a value that has it as a value, I could not find anything in the documents

**Comment by mrtaheri2** [comment]
+1

**Comment by saeedrahimi** [comment]
Hi, sorry for delay.

You should pass dayjs object with [jalali calendar](https://github.com/alibaba-aero/jalaliday).

```jsx
import dayjs from 'dayjs'

// If you want to all new instanses of dayjs use jalali calendar, you can set default calendar
dayjs.calendar('jalali');
const date = dayjs("1399-01-01", {jalali:true});

<DatePickerJalali defaultValue={date}/>
<CalendarJalali  value={date}/>
```
also you can create a jalali date without changing default calendar

```js
const date = dayjs()
const jalaliDate = date.calendar('jalali')
```

**Comment by saeedrahimi** [comment]
Readme updated.

I am closing this issue, feel free to reopen. ;)
