### ISSUE TITLE
error set default value

### ISSUE THREAD

**Issue by imani013** [saeedrahimi/antd-jalali#9]
I give an error when I try to give the default date, thank you for your help
I also used these commands to set:

const date = dayjs("1399-01-01", {jalali:true});
<DatePickerJalali defaultValue={date}/>

Or
const date = dayjs(date).calendar('jalali').locale('fa')
<DatePickerJalali defaultValue={date}/>

errors:
![image](https://user-images.githubusercontent.com/11403627/103621558-a1767000-4f4a-11eb-8037-a5850381e511.png)

**Comment by saeedrahimi** [comment]
Hi, I've just checked again and I there was no error on date-picker:
https://stackblitz.com/edit/react-ts-antd-jalali  (I don't know why locale is not working on stackblitz, but it works on other environments).

You could check your date object.

**Comment by imani013** [comment]
I get this error when I use your code

![image](https://user-images.githubusercontent.com/11403627/104119803-6b206280-5347-11eb-83e6-e9a9fc71b17a.png)

**Comment by imani013** [comment]
salam mohandes jan baz drost nashod man dobare ro git khataro frestadam
project man Nextjs hast

mamnoon misham rahnamaei konid



________________________________
